[project]
name = "okane"
dynamic = ["version"]
description = "Parser for bank statements in camt.053 XML format (Czech Banking Association dialect)"
readme = "README.md"
license = { file = "LICENSE.txt" }
authors = [
    { name = "Tomas Karabela", email = "tkarabela@seznam.cz" },
]
requires-python = ">=3.10"
keywords = ["finance", "czech", "banking", "sepa", "expenses", "camt053"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Financial and Insurance Industry",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: File Formats",
    "Topic :: Office/Business :: Financial :: Accounting",
    "Typing :: Typed",
]
dependencies = [
    "lxml>=4.9",
    "pydantic~=2.5",
]

[project.optional-dependencies]
pandas = [
    "pandas~=2.1",
    "openpyxl~=3.1",
]

[project.urls]
Homepage = "https://github.com/tkarabela/okane"
Repository = "https://github.com/tkarabela/okane"
"Bug Tracker" = "https://github.com/tkarabela/okane/issues"

[project.scripts]
okane = "okane:main"

[dependency-groups]
dev = [
    "mypy~=1.1",
    "pytest~=7.4",
    "pytest-cov~=4.0",
    "lxml-stubs~=0.4",
    "pandas-stubs~=2.1",
    "ruff~=0.15",
    "pytest-datadir>=1.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/okane/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/okane"]

[tool.hatch.build.targets.sdist]
include = [
    "src/okane",
    "README.md",
    "LICENSE.txt",
    "tests",
]

[tool.coverage.run]
branch = true

[tool.coverage.report]
show_missing = true
skip_covered = true
